# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
     - main
# on: workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # tests_e2e:
  #   runs-on: ubuntu-latest
  #   steps:
  #     # - name: Checkout and Node
  #     - uses: actions/checkout@v3
  #     - uses: pnpm/action-setup@v2
  #       with:
  #         version: latest
  #         run_install: true
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: '>=18'
  #         cache: 'pnpm'
  #     # - run: pnpm install
  #     - run: pnpm dlx playwright install --with-deps
  #    - run: pnpm run test
  deploy:
    # needs: tests_e2e
    env:
      NODE_V: 16.19.1
      PROJECT_NAME: remix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: =${{ env.NODE_V }}
          cache: 'npm'
      # - name: Install deps
      #   run: npm install

      - name: Path
        run: pwd

      # - name: List
      #   run: ls
      #
      # - name: Remix app to root
      #   run: find . ! -name 'apps' -type f -exec rm -f {} +
      #
      # - name: Path
      #   run: pwd
      #
      # - name: List
      #   run: ls -lha
      #
      # # - name: Remove all on root
      # #   run: mv -f -t . ./apps/remix/* || true 
      # #
      # # - name: Remove all on root
      # #   run: mv -f -t . ./apps/remix/.* || true
      # - name: Move
      #   run: cd ./apps/remix && find . -name . -o -exec sh -c 'mv -- "$@" "$0"' ../.. {} + -type d -prune
      #
      # - name: Path
      #   run: pwd
      #
      # - name: List
      #   run: ls -lha package.json

      # - name: Remove residual apps dir
      #   run: rm -r apps
      #
      # - name: Path
      #   run: pwd
      #
      # - name: List
      #   run: ls -lha

      - name: Install ${{ env.PROJECT_NAME }} workspace
        run: npm ci --workspace=${{ env.PROJECT_NAME }}
        # run: npm ci --workspace=${{ env.PROJECT_NAME }} --omit=dev 
        # run: npm --workspace=remix install
        # run: npm install --omit=dev 

      - name: Build ${{ env.PROJECT_NAME }}
        run: npm run build --workspace=${{ env.PROJECT_NAME }}
 
      # - name: Move Remix app to Root
      #   run: mv apps/remix .. && cd ..

      - uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_WORKERS }}
          # command: publish ./apps/remix/wrangler.toml 
          # preCommands: npm ci --workspace=remix --omit=dev
          # preCommands: npm install --workspace=remix --omit=dev
          # command: publish ./wrangler.toml 
          workingDirectory: './apps/${{ env.PROJECT_NAME }}'
          # environment: "production"
